### ISSUE TITLE
[ Feat ] 공통 컴포넌트 - 모달

### ISSUE THREAD

**Issue by ptyoiy** [GAMZA-BAT/algohub-client#11]
### 🔨 Issue

모달 컴포넌트 구현

### ✅ To-do

- user page
- [ ] create_study_modal
- [ ] accept_study_modal
- [ ] require_login_modal
- group page
- [ ] leave_study_modal
- [ ] confirm_modal
- [ ] comment_modal
