### ISSUE TITLE
solved-detail 모달 구현 (코드, 댓글 섹션)

### ISSUE THREAD

**Issue by ptyoiy** [GAMZA-BAT/algohub-client#147]
### 🔨 Issue

solved-detail을 구현합니다.

### ✅ To-do

- [ ] 코드 섹션 구현
- [ ] 코드 하이라이팅 적용
- [ ] 댓글 섹션 구현
