### ISSUE TITLE
그룹 페이지 API 연동

### ISSUE THREAD

**Issue by wuzoo** [GAMZA-BAT/algohub-client#185]
### 🔨 Issue

그룹 페이지 API 연동

### ✅ To-do

- [x] 그룹 생성
- [x] 그룹 목록 조회
- [x] 그룹 정보 조회
- [x] 그룹 회원 목록 조회
