### ISSUE TITLE
Header dropdown 구현

### ISSUE THREAD

**Issue by ptyoiy** [GAMZA-BAT/ALGOHUB-CLIENT#30]
### 🔨 Issue

Header 컴포넌트 안에 있는 알림 버튼 클릭 시 나오는 드롭다운을 구현합니다.

### ✅ To-do

- [x] 드롭다운 토글 기능 구현
- [ ] 알림 드롭다운 구현
- [ ] 프로필 드롭다운(프로필 창) 구현
