### ISSUE TITLE
공통 컴포넌트 Docs 작성 및 className 작업

### ISSUE THREAD

**Issue by ptyoiy** [GAMZA-BAT/ALGOHUB-CLIENT#65]
### 🔨 Issue

공통 컴포넌트의 경우 `children`, `props`에 사용되는 컴포넌트의 구조, 특정 props의 사용법 등을 알려줘야 할 경우 `Story`에 상세히 작성해주는 것으로 3차 회의에서 결정되었습니다. 이에 따라 사용 방법 설명이 필요한 `children`, `props 컴포넌트`는 `CSF3(Component Story Format 3)` 구조에 맞춰 render 속성의 값으로 할당할 함수 컴포넌트 내부에서 작성해주시길 바랍니다.

className 결합 함수의 경우
- [clsx](https://bundlephobia.com/package/clsx@2.1.1) → 337bytes~570bytes
- [classNames](https://bundlephobia.com/package/classnames@2.5.1) → 436bytes~752bytes
3차 회의에서 정한대로 clsx가 더 작기 때문에 clsx를 공통 컴포넌트에 적용합시다.

**#65 브랜치에서 각자 맡으셨던 컴포넌트만 처리해 주세요!**
현재 PR에 있는 컴포넌트는 해당 PR(브랜치)에서 수정하는 게 좋을 것 같습니다.

### ✅ To-do

- [ ] `props` 중 설명이 필요한 `Props`는 `type`에 작성 (Reference type 작성 예시 참조)
- [ ] `props`로 사용해야 하는 컴포넌트의 구조 설명이 필요한 경우 story에 작성 (Reference story 작성 예시 참조)
- [ ] `props`로 넣은 className이 기존에 적용 중인 것과 결합되도록 `clsx` 함수 적용

### 📄 Reference
- 작성 예시 (clsx 적용)

    <details>
    <summary>clsx 사용법</summary>
    
    [NPM](https://www.npmjs.com/package/clsx)
    
    ```typescript
    import clsx from 'clsx';
    // or
    import { clsx } from 'clsx';
    
    // Strings (variadic)
    clsx('foo', true && 'bar', 'baz');
    //=> 'foo bar baz'
    
    // Objects
    clsx({ foo:true, bar:false, baz:isTrue() });
    //=> 'foo baz'
    
    // Objects (variadic)
    clsx({ foo:true }, { bar:false }, null, { '--foobar':'hello' });
    //=> 'foo --foobar'
    
    // Arrays
    clsx(['foo', 0, false, 'bar']);
    //=> 'foo bar'
    
    // Arrays (variadic)
    clsx(['foo'], ['', 0, false, 'bar'], [['baz', [['hello'], 'there']]]);
    //=> 'foo bar baz hello there'
    
    // Kitchen sink (with nesting)
    clsx('foo', [1 && 'bar', { baz:false, bat:null }, ['hello', ['world']]], 'cya');
    //=> 'foo bar hello world cya'
    ```
    
    </details>

```typescript
const Button = ({
  children,
  className, // 1. className을 props에서 빼옵니다.
  size = "small",
  color = "purple",
  ...props
}: ButtonProps) => {
  return (
    <button
      className={clsx( // 2. 사용되는 모든 className을 clsx 함수의 인자로 넣어주면 됩니다.
        buttonStyle({
          size,
          color,
        }),
        className, // 함수의 인자로 buttonStyle과 props의 className을 넣은 모습
      )}
      {...props}
    >
      {children}
    </button>
  );
};
```

- 작성 예시 (`Menu` 컴포넌트 type)
```typescript
type MenuProps = {
  /** 두 render 컴포넌트의 `id`, `aria-label`, `aria-labelledby`속성에 사용될 string <br><hr> */
  label: string;
  /** trigger button 컴포넌트<br>
   * **부여되는 속성**: `className`, `id`, `aria-label`, `aria-haspopup`, `aria-expanded`, `aria-controls`, `onClick`, `onKeyDown`<br><hr>
   */
  renderTriggerButton: ReactNode;
  /** `<Dropdown />`으로 만들어진 리스트 컴포넌트<br>
   * **부여되는 속성**: `id`, `aria-labelledby`<br><hr>
  */
  renderList: ReactNode;
};

/** 
 * trigger button과 list에 토글 기능과 필요한 aria속성을 부여해주는 컴포넌트<br>
 * **`renderTriggerButton`은 꼭 clsx를 사용해 className을 결합해야 함**
 */
const Menu = ({ label, renderTriggerButton, renderList }: MenuProps) => {
...
```
- 적용 결과 (type)
![image](https://github.com/user-attachments/assets/8e65a9f3-e04c-453a-ac41-b6f6a04e1a7a)

- 작성 예시 (`Menu` 컴포넌트 story, 설명 필요한 주석은 여기에)
```typescript
export const LanguageWithDivTrigger: Story = {
  parameters: {
    docs: {
      source: {
        type: "dynamic",
      },
    },
  },
  render: () => {
    // 버튼의 className은 항상 clsx로 결합(Menu 컴포넌트가 기본 스타일 className을 주입해줌)
    const TriggerButton = ({ className, ...props }: ComponentProps<"div">) => {
      return (
        // <button> 외의 것을 사용할 경우 role="button"을 넣어주세요
        <div className={clsx(storyDivStyle, className)} role="button" {...props}>
          <span>모든 언어</span>{" "}
          <IcnBtnArrowDown width={"2rem"} height={"2rem"} />
        </div>
      );
    };
    return (
      <Menu
        label="language"
        renderTriggerButton={<TriggerButton />}
        renderList={
          <Dropdown>
            <li>C++</li>
            <li>Java</li>
            <li>Python</li>
            <li>C</li>
            <li>Rust</li>
          </Dropdown>
        }
      />
    );
  },
};
```
- 적용 결과 (story)
![image](https://github.com/user-attachments/assets/ac95a752-5ee3-43a5-805f-f25c267ff1bd)
