### ISSUE TITLE
Table 공통 컴포넌트 구현

### ISSUE THREAD

**Issue by ptyoiy** [GAMZA-BAT/ALGOHUB-CLIENT#78]
### 🔨 Issue

여러 페이지에서 사용될 Table 컴포넌트를 제작합니다.

### ✅ To-do

- [ ] 테이블 요소 구현 (table, thead, tbody, tfoot, tr, th, td)
- [ ] 테이블 훅 구현
  - [ ] 정렬
  - [ ] 필터링 (and 결합)
    - [ ] 검색어
    - [ ] 드롭다운 select
  - [ ] 페이지네이션
  - [ ] 셀 간격 조정(정렬)
- [ ] 페이지별 테이블 데이터 타입 정의(임시)

### 📄 Reference
**특이사항**
- 마이페이지
  - 스터디 관리
    헤더 클릭 시 그냥 정렬 (우측 상하 화살표) / 메뉴 드롭다운 정렬(좌측 화살표)
  - 알림 설정
    전체 토글, 개별 on/off
- 그룹페이지
  - 풀어야 할 문제, 문제 리스트
    3줄씩 페이지네이션, 상태에 따라 체크박스 변경
  - solved list
    검색(필터링, 드롭다운, 새로고침) => 훅으로 제공

_No response_
